# Generated by Django 3.2 on 2021-04-11 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('escudo', models.ImageField(blank=True, upload_to='escudoEquipo/')),
                ('ubicacion', models.CharField(max_length=250)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=250, unique_for_date='creado')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_equipo', to=settings.AUTH_USER_MODEL)),
                ('integrantes', models.ManyToManyField(blank=True, related_name='UsuariosIntegrantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_cuestionario', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_perteneciente', to='main.equipo')),
                ('pregunta', models.ManyToManyField(blank=True, related_name='PreguntasPertenecientes', to='main.Pregunta')),
            ],
        ),
    ]
